\=]-
;?# GNS Implementation Details

The model works by adopting a particle-based representation of the physical system. Physical dynamics are approximated by interactions among the particles. The objective of the model is to learn these interactions.

## Encoder
The encoder embeds the particle-based state representation, $X$, as a latent graph $G_0=\text{ENCODER}(X)$, where $G=(V,E,\mathbf{u})$, $\mathbf{v}_i\in V$, and $\mathbf{e}_{i,j}\in E$.
- The encoder constructs the graph structure $G^0$ by assignning a node to each particle and adding edges between particles within a connectivity radius, $R$. On each timestep the graph's edges are recomputed by a nearest neighbor algorithm, implemented by a standard kd-tree, to reflect the current particle positions.
- The node embeddings, $\mathbf{v}_i=\varepsilon ^v(x_i)$, are learned functions of the particles' states.
- The edge embeddings, $\mathbf{e}_{i,j}=\varepsilon^e(\mathbf{r}_{i,j})$, are learned functions of the pairwise properties of the corresponding particles, $\mathbf{r}_{i,j}$, e.g., displacement between their positions, spring constant, etc.
- $\varepsilon^v$ and $\varepsilon^e$ as a multilayer perceptron, which encode node features and edge features into the latent vectors, $v_i$ and $e_{i,j}$, of size $128$.
- The graph-level embedding, $\mathbf{u}$, could represent global properties such as gravity and magnetic fields. Although, this is currently implemented as node level features instead.
- There are 2 variants of the encoder:
    - In the absolute variant the input to the edge model $\varepsilon^{e}$ is discarded, and $\mathbf{e}^0_{i,j}$ is set to a trainable fixed bias vector instead.
    - The relative encoder variant is designed to impose an inductive bias of invariance to absolute spatial location. The node model $\varepsilon^{v}$ is forced to ignore $\mathbf{p}_i$ information within $x_i$ by masking it out. The edge model $\varepsilon^{e}$ is provided with the relative positional displacement, and it's magnitude,  $r_{i,j}=[(\mathbf{p}_i-\mathbf{p}_j),\lVert\mathbf{p}_i-\mathbf{p}_j\rVert]$


## Neural network parameters
- All MLPs have **2 hidden layers** with **ReLU** activations, followed by a non-activated output layer, each layer with size **128**.
- All MLPs, except the output decoder, are followed by a **LayerNorm** layer.



In [24]:
# setup autoreload
%load_ext autoreload
#%autoreload 2
# Change working directory to root directory
%cd "/workspace"

/workspace


In [67]:
%%writefile open_gns/models/encoder.py

import torch
from torch.nn import Sequential, Linear, ReLU, LayerNorm
from torch_geometric.nn import MetaLayer

def make_mlp(input_size, hidden_size=128, output_size=128, layer_norm=True):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    layers = [
        Linear(input_size, hidden_size),
            ReLU(),
            Linear(hidden_size, hidden_size),
            ReLU(),
            Linear(hidden_size, output_size),
    ]
    if layer_norm:
        layers.append(LayerNorm(output_size))
    return Sequential(*layers).to(device)

class EdgeModel(torch.nn.Module):
    def __init__(self, input_size, hidden_size=128):
        super(EdgeModel, self).__init__()
        self.edge_mlp = make_mlp(input_size, hidden_size)

    def forward(self, src, dest, edge_attr, u, batch):
        features = [src, dest] if edge_attr is None else [src, dest, edge_attr]
        out = torch.cat(features, 1)
        return self.edge_mlp(out)

class NodeModel(torch.nn.Module):
    def __init__(self, input_size, hidden_size=128):
        super(NodeModel, self).__init__()
        self.node_mlp = make_mlp(input_size, hidden_size)

    def forward(self, x, edge_index, edge_attr, u, batch):
        # TODO: Do we need to combine with edge_attr?
        return self.node_mlp(x)


class Encoder(torch.nn.Module):
    def __init__(self, input_size, output_size=128):
        super(Encoder, self).__init__()
        self.encoder = MetaLayer(EdgeModel(2*input_size), NodeModel(input_size))

    def forward(self, x, edge_index):
        # TODO: The encoder needs to build the Graph
        # otherwise the graph would need to be pre-built
        return self.encoder(x, edge_index)

    
class RelativeEdgeModel(torch.nn.Module):
    def __init__(self, hidden_size=128):
        super(RelativeEdgeModel, self).__init__()
        self.edge_mlp = make_mlp(4, hidden_size)

    def forward(self, src, dest, edge_attr, u, batch):
        distance = src[:,0:3] - dest[:,0:3]
        magnitude = torch.norm(distance, dim=1, keepdim=True)
        out = torch.cat([distance, magnitude], 1)
        return self.edge_mlp(out)


class RelativeNodeModel(torch.nn.Module):
    def __init__(self, input_size, hidden_size=128):
        super(RelativeNodeModel, self).__init__()
        self.node_mlp = make_mlp(input_size, hidden_size)

    def forward(self, x, edge_index, edge_attr, u, batch):
        masked = x.clone()
        masked[:,0:3] = 0
        return self.node_mlp(x)

    
class RelativeEncoder(torch.nn.Module):
    def __init__(self, input_size, output_size=128):
        super(RelativeEncoder, self).__init__()
        self.encoder = MetaLayer(RelativeEdgeModel(), RelativeNodeModel(input_size))

    def forward(self, x, edge_index):
        return self.encoder(x, edge_index)
    
    


Overwriting open_gns/models/encoder.py


In [45]:
a = torch.randn(2,4)
b = torch.norm(a,dim=1,keepdim=True)
c = torch.cat([a,b], 1)
print(a)
print(b)
print(c)

tensor([[-0.2454, -0.7263,  0.2144,  0.0836],
        [ 0.3430,  0.7757,  1.0537, -0.8873]])
tensor([[0.8004],
        [1.6177]])
tensor([[-0.2454, -0.7263,  0.2144,  0.0836,  0.8004],
        [ 0.3430,  0.7757,  1.0537, -0.8873,  1.6177]])


In [56]:
%autoreload 2
# Testing the Encoder
from open_gns.dataset import GNSDataset
from open_gns.models.encoder import RelativeEncoder
# Load dataset
dataset = GNSDataset('./notebooks')
print(f'Samples: {len(dataset)}, Num node features: {dataset.num_node_features}')
data = dataset[0]
input_size= dataset.num_node_features

encoder = RelativeEncoder(input_size)
data.to('cuda' if torch.cuda.is_available() else 'cpu')
x, e, u = encoder(data.x.float(), data.edge_index)
print(x.size(), e.size())

Samples: 111683, Num node features: 25
input_size: 25
0 0 0 0
torch.Size([1024, 128]) torch.Size([15440, 128])


## Processor
The *PROCESSOR* performs $M$ rounds of learned message-passing over the latent graphs, $G^0, ..., G^M$. This is implemented by a stack of $M$ GNs with identical structure, MLPs as internal edge and node update functions, and either shared or unshared parameters. GNs are used without global features or global updates, and with a residual connection between the input and output latent node and edge attributes.

In [61]:
%%writefile open_gns/models/processor.py

import torch
from torch_geometric.nn import MetaLayer
from open_gns.models.encoder import EdgeModel, NodeModel

class Processor(torch.nn.Module):
    def __init__(self, input_size, output_size=128, M=10):
        super(Processor, self).__init__()
        self.GNs = torch.nn.ModuleList([])
        for i in range(M):
            GN = MetaLayer(EdgeModel(3*input_size), NodeModel(input_size))
            self.GNs.append(GN) 

    def forward(self, x, edge_index, edge_attr):
        for GN in self.GNs:
            # TODO: Concatenate residuals instead?
            # Keep residuals
            node_residual = x
            edge_residual = edge_attr
            # Apply GN
            x, edge_attr, u = GN(x, edge_index, edge_attr)
            # Add residuals
            x = x + node_residual
            edge_attr = edge_attr + edge_residual
        return x, edge_attr, u

Overwriting open_gns/models/processor.py


In [62]:
# Testing the processor
from open_gns.models.processor import Processor

processor = Processor(128)
print(e.size())
x, e, u = processor(x, data.edge_index, e)
print(x.size(), e.size())

torch.Size([15440, 128])
torch.Size([1024, 128]) torch.Size([15440, 128])


## Decoder
The *DECODER* extracts dynamic information from the nodes of the final latent graph, $G^M$, produced by the *PROCESSOR*. The decoder's learned function, $\delta^v$, is an MLP. After the *DECODER*, the future position and velocity are updated using an Euler integrator, so the $\mathbf{y}_i$ corresponds to accelerations, $\ddot{p}^t_i$.

In [63]:
%%writefile open_gns/models/decoder.py

import torch
from open_gns.models.encoder import make_mlp

class Decoder(torch.nn.Module):
    def __init__(self, input_size):
        super(Decoder, self).__init__()
        self.decoder = make_mlp(input_size, output_size=3, layer_norm=False)
    
    def forward(self, x):
        return self.decoder(x)



Overwriting open_gns/models/decoder.py


In [70]:
from open_gns.models.decoder import Decoder
# Test the decoder
decorder = Decoder(input_size=x.size(1))
out = decorder(x)
print(out.size())

torch.Size([1024, 3])


In [68]:
%%writefile open_gns/models/__init__.py
import torch
from open_gns.models.encoder import RelativeEncoder
from open_gns.models.processor import Processor
from open_gns.models.decoder import Decoder

class EncodeProcessDecode(torch.nn.Module):
    def __init__(self, input_size, hidden_size=128):
        super(EncodeProcessDecode, self).__init__()
        self.encoder = RelativeEncoder(input_size)
        self.processor = Processor(hidden_size)
        self.decoder = Decoder(hidden_size)

    def forward(self, x, edge_index):
        x, edge_attr, _ = self.encoder(x, edge_index)
        x, edge_attr, _ = self.processor(x, edge_index, edge_attr)
        return self.decoder(x)

Overwriting open_gns/models/__init__.py


In [71]:
gns = EncodeProcessDecode(input_size)
y = gns(data.x.float(), data.edge_index)
print(y.size())

TypeError: super(type, obj): obj must be an instance or subtype of type

# Parameters
Parameters for BoxBath:

- Connectivity radius: $R=0.08$